const express = require('express')
const app = express()
const cors = require('cors')
const authenticate = require('./Database/authentication')
const createTables = require('./Database/createTables')
const cadastroUsuarioAPI = require('./API/usuarios/cadastrar')
const loginUsuarioAPI = require('./API/usuarios/logar')
const adicionarEventoAPI = require('./API/eventos/adicionar')
const editarEventoAPI = require('./API/eventos/editar')
const listarTodosEventosAPI = require('./API/eventos/listarTodosEventos')
const listarMeusEventosAPI = require('./API/eventos/listarMeusEventos')
const deletarEventosAPI = require('./API/eventos/deletar')
const inscreverEventoAPI = require('./API/eventos/inscrever')

app.use(cors())
app.listen(3001, () => {
    console.log('backend rodando porta: 3001')
})
app.post('/usuario/cadastrar', cadastroUsuarioAPI)
app.post('/usuario/logar', loginUsuarioAPI)
app.post('/evento/adicionar', adicionarEventoAPI)
app.post('/evento/editar', editarEventoAPI)
app.post('/evento/deletar', deletarEventosAPI)
app.get('/evento/listarTodosEventos', listarTodosEventosAPI)
app.get('/evento/listarMeusEventos/:idUsuario', listarMeusEventosAPI)
app.post('/evento/meinscrever', inscreverEventoAPI)

